name: Test Xormtest
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Golang Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Misspelling
      run: |
        go get github.com/client9/misspell/cmd/misspell
        misspell -error .

    - name: Test
      run: |
        go test ./...
